using UnityEngine;

public class Arrow : MonoBehaviour
{
    GameObject target;
    Vector3 moveDir; // 이동방향 벡터
    float moveSpeed = 3f; //화살 이동 속도
    float damage = 10f; //화살 데미지
    private void Start()
    {
        Enemy enemy = FindObjectOfType<Enemy>();
        if(enemy != null)
        {
            target = enemy.gameObject; // 타겟을 적의 오브젝트로 설정
            moveDir = target.transform.position - transform.position; // 이동 방향 벡터를 계산
            moveDir.Normalize(); // 이동 방향 벡터 정규화
        }
    }

    // Update is called once per frame
    void Update()
    {
        if (target == null)
        {
            Destroy(gameObject);
        }
        transform.position += moveDir * moveSpeed * Time.deltaTime;
    }

    private void OnTriggerEnter2D(Collider2D collision) // 충돌했을 때
    {
        Enemy enemy = collision.GetComponent<Enemy>(); // 적의 Enemy 스크립트를 참조한다.
        if (enemy.gameObject == target) // 충돌한 상대가 내가 목표하는 적일 때,
        {
            enemy.health -= damage; // 충돌한 적의 체력을 데미지만큼 감소시키는 코드
            if (enemy.health <= 0) // 적 체력이 0 이하인 경우
            {
                Destroy(collision.gameObject); // 적 게임 오브젝트를 지운다.
                                               // 적 게임 오브젝트를 지운다.
                                               //collision.gameObject.SetActive(false); // 적 게임 오브젝트를 끈다.
                                               //gameObject.SetActive(false); // 본인 오브젝트도 끈다.

            }
            Destroy(gameObject);
        }

    }
}

